/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 chair.gltf
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    ArmChair_01: THREE.Mesh;
  };
  materials: {
    Armchair_01: THREE.MeshStandardMaterial;
  };
};

type ModelProps = JSX.IntrinsicElements['group'] & {
  selectedMaterial: THREE.MeshPhysicalMaterial;
};

const Chair = ({ selectedMaterial, ...props }: ModelProps) => {
  const { nodes } = useGLTF('/chair/chair.gltf') as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ArmChair_01.geometry} material={selectedMaterial} />
    </group>
  );
};

useGLTF.preload('/chair/chair.gltf');

export default Chair;
